---
- name: vscode role
  tags:
    - vscode
  block:
  
  # mkdir
  - name: Make sure directory exists {{ vscode_apt_repo_key_dst | dirname }}
    become: true
    ansible.builtin.file:
      path: "{{ vscode_apt_repo_key_dst | dirname }}"
      mode: u=rwx,g=rx,o=rx
      state: directory
      
  # repo key
  - name: Copy repo key to {{ vscode_apt_repo_key_dst }}
    become: true
    ansible.builtin.copy:
      src: microsoft-vscode.gpg
      dest: "{{ vscode_apt_repo_key_dst }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  # template repo file
  - name: Template repo file to /etc/apt/sources.list.d/{{ vscode_apt_repo_template.replace('.j2', '') }}
    become: true
    ansible.builtin.template:
      src: "{{ vscode_apt_repo_template }}"
      dest: "/etc/apt/sources.list.d/{{ vscode_apt_repo_template.replace('.j2', '') }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    register: __vscode_repo
  
  # apt-update
  - when: __vscode_repo.changed
    name: Update apt cache
    become: true
    ansible.builtin.apt:
      update_cache: true
  
  # install
  - name: Install vscode
    become: true
    ansible.builtin.apt:
      state: present
      name: code
  
  # vscode_settings
  - when: vscode_settings != None
    name: Copy settings to /home/{{ vscode_user }}/.config/Code/User/settings.json
    become: true
    ansible.builtin.copy:
      src: "{{ vscode_settings }}"
      dest: "/home/{{ vscode_user }}/.config/Code/User/settings.json"
      owner: "{{ vscode_user }}"
      group: "{{ vscode_user }}"
      mode: u=rw,g=,o=

  # vscode_settings
  - when: vscode_keybindings != None
    name: Copy keybindings to /home/{{ vscode_user }}/.config/Code/User/keybindings.json
    become: true
    ansible.builtin.copy:
      src: "{{ vscode_keybindings }}"
      dest: "/home/{{ vscode_user }}/.config/Code/User/keybindings.json"
      owner: "{{ vscode_user }}"
      group: "{{ vscode_user }}"
      mode: u=rw,g=,o=
